#ifndef OS_WRAPPER_H
#define OS_WRAPPER_H

#define MODULE_NAME "StrongholdLegends.exe"
#define AWARD_1 "True Dedication"
#define AWARD_2 "Grand Designer"
#define AWARD_3 "King of the Hill"
#define AWARD_4 "Capture the Flag"
#define AWARD_5 "Economic War"
#define AWARD_6 "Deathmatch"
#define AWARD_7 "King of Camelot"
#define AWARD_8 "Champion of the North"
#define AWARD_9 "Lord of Darkness"
#define AWARD_10 "The Valley of Flowers"
#define AWARD_11 "The Long March"
#define AWARD_12 "The Road to Hell"
#define AWARD_13 "Arthur's Challenge"
#define AWARD_14 "Skirmish Warlord"
#define AWARD_15 "Multiplayer Warlord"
#define AWARD_16 "Small Skirmish Streak"
#define AWARD_17 "Big Skirmish Streak"
#define AWARD_18 "Huge Skirmish Streak"
#define AWARD_19 "Small Multiplayer Streak"
#define AWARD_20 "Big Multiplayer Streak"
#define AWARD_21 "Huge Multiplayer Streak"
#define AWARD_22 "AI Destroyer"
#define AWARD_23 "Human Destroyer"
#define AWARD_24 "Dragon Slayer"
#define AWARD_25 "Grand Dragon Slayer"
#define AWARD_26 "Dragon Summoner"
#define AWARD_27 "Grand Dragon Summoner"
#define AWARD_28 "Glory Seeker"
#define AWARD_29 "King Arthur"
#define AWARD_30 "Vlad the Impaler"
#define AWARD_31 "Dietrich"
#define AWARD_32 "Melee Hero"
#define AWARD_33 "Ranged Hero"
#define AWARD_34 "Siegeless"
#define AWARD_35 "The Ultimate Lord"
#define AWARD_36 "Finance King"
#define AWARD_37 "Economic King"
#define AWARD_38 "Military King"
#define AWARD_39 "Creeper Award"
#define AWARD_40 "Estate Stealer"
#define AWARD_41 "Arthur Dedication"
#define AWARD_42 "Ice Dedication"
#define AWARD_43 "Evil Dedication"
#define AWARD_44 "Drunk's Award"
#define AWARD_45 "Priest's Award"
#define AWARD_46 "Feaster's Award"
#define AWARD_47 "Greed Award"
#define AWARD_48 "Generosity Award"
#define AWARD_49 "Granary Filler"
#define AWARD_50 "Defensive Master"
#define AWARD_51 "Castle Builder"
#define AWARD_52 "The Ultimate Castle"
#define AWARD_53 "The Ultimate Farmer"
#define AWARD_54 "The Ultimate Worker"
#define AWARD_54 "The Ultimate Worker"
#define AWARD_55 "Chivalry Award"
#define AWARD_56 "Fanboys Award"
#define AWARD_57 "Unit Lover"
#define AWARD_58 "Body Count"
#define AWARD_59 "Total Destruction"
#define AWARD_60 "Legend"

long getshpid(void);
long get_opcode_address(long);
void overwrite_opcode(long, long, unsigned long long, int);

#endif /* OS_WRAPPER_H */
